name: Canvas to Notion Sync

on:
  schedule:
    - cron: '0 * * * *' # Roda a cada 1 hora
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: node index.js
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_ASSIGNMENTS_DB_ID: ${{ secrets.NOTION_ASSIGNMENTS_DB_ID }}
          CANVAS_TOKEN: ${{ secrets.CANVAS_TOKEN }}